import type { AdminTrainingRoute } from "./types";

export const ADMIN_TRAINING_MAP: AdminTrainingRoute[] = [
  { id: "dashboard", route: "/admin", name: "Табло", purpose: "Ежедневен общ преглед.", audience: "Всички администратори с достъп до Таблото.", permission: "DASHBOARD:VIEW", topicId: "dashboard", controlsFound: ["Добави нов продукт", "Виж всички", "Отвори склада", "Карти със статистика", "Графики", "Последни поръчки", "Ниска наличност"], relatedRoutes: ["/admin/orders", "/admin/inventory", "/admin/products/new"] },
  { id: "access-denied", route: "/admin/access-denied", name: "Ограничен достъп", purpose: "Обяснява липсващо право.", audience: "Подадминистратори.", topicId: "access-denied", controlsFound: ["Към профила"], relatedRoutes: ["/admin/administrators"] },
  { id: "accounting", route: "/admin/accounting", name: "Вътрешно счетоводство", purpose: "Управленски отчет за приходи, себестойност и печалба.", audience: "Собственик и счетоводен персонал.", permission: "ACCOUNTING:VIEW", topicId: "internal-accounting", controlsFound: ["Период", "Генерирай PDF", "Обобщения", "По плащане", "По статус", "Дневна разбивка", "Поръчки"], relatedRoutes: ["/admin/accounting/official", "/admin/orders"] },
  { id: "official-accounting", route: "/admin/accounting/official", name: "Официален отчет", purpose: "Регистър на платени продажби и финализирани възстановявания.", audience: "Собственик и счетоводител.", permission: "ACCOUNTING:VIEW", topicId: "official-accounting", controlsFound: ["Вътрешен отчет", "Период", "PDF / печат", "Фирмени данни", "ДДС обобщения", "Хронологичен регистър"], relatedRoutes: ["/admin/accounting", "/admin/legal-settings"] },
  { id: "administrators", route: "/admin/administrators", name: "Администратори", purpose: "Роли, акаунти и права.", audience: "Главни администратори.", permission: "ADMINISTRATORS:VIEW", topicId: "administrators", controlsFound: ["Търси потребител", "Съществуващ акаунт", "Добави права", "Права", "Премахни права", "Всички", "Изчисти всички", "Запази", "Затвори", "Редакция на акаунт"], relatedRoutes: ["/admin/audit-log", "/admin/access-denied"] },
  { id: "audit-log", route: "/admin/audit-log", name: "Дневник", purpose: "Проследява последните административни действия.", audience: "Главни администратори и контрол.", permission: "AUDIT_LOG:VIEW", topicId: "audit", controlsFound: ["Списък с действие", "Описание", "Извършител", "Дата и час"], relatedRoutes: ["/admin/administrators", "/admin/system-health"] },
  { id: "catalog-categories", route: "/admin/catalog-categories", name: "Категории / филтри", purpose: "Управлява филтрите вътре в секциите.", audience: "Каталожен персонал.", permission: "PRODUCTS:VIEW", topicId: "catalog-categories", controlsFound: ["Търси категория", "Филтър по секция", "Име", "Slug", "Секция", "Създай", "Запази", "Изтрий", "Странициране по 5"], relatedRoutes: ["/admin/catalog-sections", "/admin/products/new"] },
  { id: "catalog-sections", route: "/admin/catalog-sections", name: "Секции / страници", purpose: "Управлява реалните магазинни страници.", audience: "Каталожен и дизайн персонал.", permission: "PRODUCTS:VIEW", topicId: "catalog-sections", controlsFound: ["Търси секция", "Име", "Страница", "Малък надпис", "Описание", "Активна", "Създай секция", "Запази", "Нагоре", "Надолу", "Изтрий"], relatedRoutes: ["/admin/catalog-categories", "/visual-editor"] },
  { id: "catalog-structure", route: "/admin/catalog-structure", name: "Каталог", purpose: "Вход към секции и категории.", audience: "Каталожен персонал.", permission: "PRODUCTS:VIEW", topicId: "catalog-overview", controlsFound: ["Секции / страници", "Категории / филтри"], relatedRoutes: ["/admin/catalog-sections", "/admin/catalog-categories"] },
  { id: "cms", route: "/admin/cms", name: "Content Model Studio", purpose: "Owner-only модели за динамично съдържание.", audience: "Само собственикът на дизайна.", designOwnerOnly: true, topicId: "cms-models", controlsFound: ["Нов модел", "Име множествено", "Име единствено", "Slug", "Икона", "Описание", "Статус", "Добави поле", "Име на поле", "Ключ", "Тип", "Задължително", "Уникално", "Премахни", "Отказ", "Запази", "Съдържание", "Изтрий"], relatedRoutes: ["/admin/cms/:id", "/visual-editor"] },
  { id: "cms-entry", route: "/admin/cms/:id", name: "CMS съдържание", purpose: "Записи в избран динамичен модел.", audience: "Само собственикът на дизайна.", designOwnerOnly: true, topicId: "cms-entries", controlsFound: ["Content Models", "Нов запис", "Търсене", "Статус филтър", "Заглавие", "Slug", "Статус", "Динамични полета", "Отказ", "Създай запис", "Запази", "Изтрий"], relatedRoutes: ["/admin/cms"] },
  { id: "customers", route: "/admin/customers", name: "Клиенти и отношения", purpose: "CRM списък и клиентска стойност.", audience: "Обслужване и търговски персонал.", permission: "CUSTOMERS:VIEW", topicId: "customers", controlsFound: ["Търсене", "CRM статус", "Сортиране", "Филтрирай", "Изчисти", "Клиентски ред", "Обобщения"], relatedRoutes: ["/admin/customers/:id", "/admin/users"] },
  { id: "customer-detail", route: "/admin/customers/:id", name: "Клиентско CRM досие", purpose: "Контакти, покупки, статус, бележки и тагове.", audience: "Обслужване и CRM персонал.", permission: "CUSTOMERS:VIEW", topicId: "customer-detail", controlsFound: ["CRM статус", "Запази CRM статуса", "Обща бележка", "Запази бележка", "Хронологична бележка", "Добави бележка", "Таг", "Добави", "Премахни таг", "Блокирай / активирай"], relatedRoutes: ["/admin/customers", "/admin/orders"] },
  { id: "help", route: "/admin/help", name: "Помощник", purpose: "Пълно самообучение и речник.", audience: "Всички администратори.", topicId: "staff-self-training", controlsFound: ["Ръководство", "Тълковен речник", "Търсене", "Смени темата", "Accordion секции"], relatedRoutes: ["/admin"] },
  { id: "inventory", route: "/admin/inventory", name: "Склад", purpose: "Наличност по вариант и резервации.", audience: "Складов персонал.", permission: "INVENTORY:VIEW", topicId: "inventory", controlsFound: ["Търсене", "Наличност", "Сортиране", "Изчисти", "Странициране по 10", "Предишна страница", "Следваща страница", "Маркирай всичко", "Прегледано", "Коригирай", "Склад", "Резервирани", "Свободни", "Продадени"], relatedRoutes: ["/admin/products/:id/edit", "/admin/orders"] },
  { id: "legal", route: "/admin/legal-settings", name: "Фирмени и legal настройки", purpose: "Фирмени данни, ДДС и публични условия.", audience: "Собственик и упълномощен персонал.", permission: "LEGAL_SETTINGS:VIEW", topicId: "legal", controlsFound: ["Фирмени полета", "ДДС режим Не / Да", "ДДС номер", "ДДС ставка", "Запази"], relatedRoutes: ["/admin/accounting/official"] },
  { id: "marketing", route: "/admin/marketing-integrations", name: "Маркетинг интеграции", purpose: "Google, Meta и TikTok идентификатори и събития.", audience: "Собственик или маркетинг специалист.", permission: "PRODUCTS:VIEW", topicId: "marketing", controlsFound: ["Активирай интеграцията", "ID", "Тестов режим", "Събития", "Запази"], relatedRoutes: ["/admin/social-networks", "/admin/system-health"] },
  { id: "orders", route: "/admin/orders", name: "Поръчки", purpose: "Обработка от нова поръчка до доставка или отказ.", audience: "Продажби, склад и обслужване.", permission: "ORDERS:VIEW", topicId: "orders", controlsFound: ["Търсене", "Мин. сума", "Макс. сума", "Сортиране", "Изчисти", "Статус филтри", "Странициране по 5", "Виж детайли", "Изтегли PDF", "Създай товарителница", "Потвърди", "Маркирай изпратена", "Маркирай доставена", "Откажи", "Откажи и върни наличността", "Tracking линк"], relatedRoutes: ["/admin/support", "/admin/inventory", "/admin/accounting"] },
  { id: "attributes", route: "/admin/product-attributes", name: "Продуктови стойности", purpose: "Готови типове, цветове и материали.", audience: "Каталожен персонал.", permission: "PRODUCTS:VIEW", topicId: "product-attributes", controlsFound: ["Име", "Добави тип", "Добави цвят", "Добави материал", "Активен", "Нагоре", "Надолу", "Изтрий", "Запази"], relatedRoutes: ["/admin/products/new", "/admin/products/:id/edit"] },
  { id: "promo-codes", route: "/admin/promo-codes", name: "Промокодове", purpose: "Създава кодове за отстъпка при checkout.", audience: "Собственик и каталожен/маркетинг персонал.", permission: "PRODUCTS:VIEW", topicId: "promo-codes", controlsFound: ["Име на промокода", "Отстъпка за стоки без намаление", "Отстъпка за вече намалени стоки", "Активен промокод", "Създай промокода", "Търсене", "Статус", "Страници", "Предишна страница", "Следваща страница", "Редактирай", "Изтрий"], relatedRoutes: ["/admin/products", "/checkout"] },
  { id: "products", route: "/admin/products", name: "Продукти", purpose: "Търсене, филтриране и управление на каталога.", audience: "Каталожен персонал.", permission: "PRODUCTS:VIEW", topicId: "products", controlsFound: ["Добави продукт", "Търсене", "Секция", "Тип", "Категория", "Марка", "Размер", "Статус", "Наличност", "Мин. цена", "Макс. цена", "Сортиране", "Филтри", "Изчисти", "Покажи", "Страници", "Предишна страница", "Следваща страница", "Редактирай", "Изтрий"], relatedRoutes: ["/admin/products/new", "/admin/products/:id/edit", "/admin/inventory"] },
  { id: "product-new", route: "/admin/products/new", name: "Добави продукт", purpose: "Създава нов артикул и варианти.", audience: "Каталожен персонал с право за създаване.", permission: "PRODUCTS:CREATE", topicId: "product-create", controlsFound: ["Име", "Марка", "Секция", "Категория", "Тип", "Цвят", "Материали", "Проценти", "Добави материал", "Описание", "Цена", "Стара цена", "Нов", "Препоръчан", "Активен", "Снимки", "Направи основна", "Премахни", "Стандартни / индивидуални размери", "Размерна таблица", "Размер", "Бройки", "Създай продукта"], relatedRoutes: ["/admin/products", "/admin/sizes", "/admin/product-attributes"] },
  { id: "product-edit", route: "/admin/products/:id/edit", name: "Редактирай продукт", purpose: "Променя съществуващ артикул и варианти.", audience: "Каталожен персонал с право за редакция.", permission: "PRODUCTS:EDIT", topicId: "product-edit", controlsFound: ["Име", "Марка", "Секция", "Категория", "Тип", "Цвят", "Материали", "Проценти", "Описание", "Цена", "Стара цена", "Нов", "Препоръчан", "Активен", "Снимки", "Размери", "Бройки", "Запази промените"], relatedRoutes: ["/admin/products", "/admin/inventory"] },
  { id: "sizes", route: "/admin/sizes", name: "Размери", purpose: "Многократни европейски размерни таблици.", audience: "Каталожен персонал.", permission: "PRODUCTS:VIEW", topicId: "sizes", controlsFound: ["Име", "Тип артикул", "Описание", "Как се измерва", "Показвай схема", "Добави измерване", "Маркер", "Единица", "Добави EU размер", "Стойности", "Запази", "Откажи редакцията", "Търсене", "Тип", "Схема", "Коригирай", "Покажи / скрий схема", "Изтрий"], relatedRoutes: ["/admin/products/new", "/admin/products/:id/edit"] },
  { id: "social", route: "/admin/social-networks", name: "Социални мрежи", purpose: "Публични линкове и иконки към профили.", audience: "Собственик или маркетинг специалист.", permission: "PRODUCTS:VIEW", topicId: "social", controlsFound: ["Покажи иконката", "Линк към профил", "Отвори профила", "Запази"], relatedRoutes: ["/admin/marketing-integrations"] },
  { id: "support", route: "/admin/support", name: "Запитвания и рекламации", purpose: "Чат, клиентски отговори и RMA обработка.", audience: "Обслужване на клиенти.", permission: "ORDERS:VIEW", topicId: "support-rma", controlsFound: ["Търсене", "Странициране по 10 разговора", "Разговор", "Статус на разговора", "RMA филтри", "Одобрено количество", "Решение", "Refund сума", "Върни автоматичната", "Tracking", "Инструкции", "В обработка", "Одобри", "Откажи", "Получено", "Сумата е възстановена", "Приключи", "Отговор", "Прикачи файлове", "Премахни файл", "Изпрати отговор"], relatedRoutes: ["/admin/orders", "/admin/inventory", "/admin/accounting"] },
  { id: "system-health", route: "/admin/system-health", name: "Системно здраве", purpose: "Проверки за база, услуги и конфигурация.", audience: "Главен администратор и технически отговорник.", permission: "SYSTEM_HEALTH:VIEW", topicId: "system-health", controlsFound: ["Обнови проверките", "Общ статус", "Database", "Cloudinary", "Resend", "Session secret", "Предупреждения"], relatedRoutes: ["/admin/audit-log"] },
  { id: "users", route: "/admin/users", name: "Потребители", purpose: "Акаунти, верификация и лични данни.", audience: "Обслужване и акаунт администрация.", permission: "CUSTOMERS:VIEW", topicId: "users", controlsFound: ["Търсене", "Статус", "Филтрирай", "Изчисти", "Потвърди акаунта ръчно", "Verification code", "Профилни данни", "Terms версия"], relatedRoutes: ["/admin/customers"] },
  { id: "web-design-redirect", route: "/admin/web-design", name: "Уеб дизайн", purpose: "Пренасочва към Визуалния редактор.", audience: "Само собственикът на дизайна.", designOwnerOnly: true, topicId: "visual-editor", controlsFound: [], relatedRoutes: ["/visual-editor"], redirectTo: "/visual-editor" },
  { id: "visual-editor", route: "/visual-editor", name: "Визуален редактор", purpose: "Променя и публикува клиентския дизайн.", audience: "Само собственикът на дизайна.", designOwnerOnly: true, topicId: "visual-editor", controlsFound: ["Страница", "Хронология", "Запиши", "Публикувай", "Затвори", "Устройство", "Размер", "Zoom", "Побери", "Избор", "Текст", "Снимка", "Секции", "Меню", "Лого", "Цветове", "Footer", "Качване", "Премахване", "Добави секция", "Добави бутон", "Видимост", "Линк", "Нова версия", "Избери тема", "Изтрий версия", "Rollback"], relatedRoutes: ["/admin/catalog-sections", "/admin/cms"] },
];

function routeSegments(path: string) {
  return path.split("?")[0].replace(/\/$/, "").split("/").filter(Boolean);
}

export function matchesAdminTrainingRoute(pattern: string, pathname: string) {
  const expected = routeSegments(pattern);
  const actual = routeSegments(pathname);
  if (expected.length !== actual.length) return false;
  return expected.every((segment, index) => segment.startsWith(":") || segment === actual[index]);
}

export function getAdminTrainingRoute(pathname: string) {
  return ADMIN_TRAINING_MAP
    .filter((route) => matchesAdminTrainingRoute(route.route, pathname))
    .sort((a, b) => b.route.length - a.route.length)[0];
}
