ALTER TABLE "SizeGuideMeasurement"
ADD COLUMN "startX" DOUBLE PRECISION NOT NULL DEFAULT 24,
ADD COLUMN "startY" DOUBLE PRECISION NOT NULL DEFAULT 30,
ADD COLUMN "endX" DOUBLE PRECISION NOT NULL DEFAULT 76,
ADD COLUMN "endY" DOUBLE PRECISION NOT NULL DEFAULT 30;
