import { button, control, field, selectControl, toggleControl, topic, workflow } from "../builders";

export const DESIGN_MARKETING_HELP_SECTIONS = [
  topic({
    id: "marketing",
    title: "Маркетинг интеграции: Google, Meta и TikTok",
    shortTitle: "Маркетинг интеграции",
    hrefs: ["/admin/marketing-integrations"],
    permission: "PRODUCTS:VIEW",
    summary: "ID-та, cookie consent, test mode и пет реални tracking събития.",
    purpose: "Настройва външните marketing providers без поставяне на ръчен JavaScript и ги зарежда само при подходящо cookie съгласие.",
    beginner: "Ако си тук за първи път, ID е кратък идентификатор от официалния Google, Meta или TikTok account. Не поставяй цели JavaScript snippets. Най-важно е ID-то да е за правилния production property/pixel и да започнеш с Тестов режим. Не активирай tracking без потвърдена cookie и privacy процедура.",
    whenToUse: ["За Google Tag/Analytics ID, Meta Pixel ID или TikTok Pixel ID.", "За включване на разрешени tracking events.", "За test mode преди production activation."],
    whenNotToUse: ["За поставяне на произволен JavaScript.", "Без owner/marketing approval.", "За заобикаляне на cookie consent."],
    screen: ["Три provider карти с consent група и status.", "Enabled, ID и Test mode за всеки provider.", "Пет event checkbox-а и Save горе/долу."],
    controls: [
      toggleControl("Активирай интеграцията", "Разрешава конкретния provider, но той е реално активен само при непразно ID и подходящо cookie consent.", "След Save provider status става Активна, ако ID е валидно непразно.", { permission: "PRODUCTS:EDIT", customerImpact: "При дадено cookie съгласие storefront може да зареди външния tracking script." }),
      field("ID на интеграцията", "Свързва магазина с конкретния analytics/pixel property.", "Google: G-XXXXXXXXXX или GTM-XXXXXXX; Meta: цифров Pixel ID; TikTok: издадения Pixel ID. Не поставяй script tag.", "G-ABC1234567", "След Save ID се използва само за активния provider според consent.", { permission: "PRODUCTS:EDIT", customerImpact: "Tracking data се изпраща към свързания външен акаунт при разрешение.", avoid: ["Не използвай ID от чужд бизнес, demo property или screenshot."] }),
      toggleControl("Тестов режим", "Показва събитията в browser console, без да зарежда външен pixel.", "След Save можеш да провериш event flow без production изпращане.", { permission: "PRODUCTS:EDIT", customerImpact: "В test mode външният pixel не се зарежда от тази интеграция." }),
      ...[
        ["Разглеждане на страница", "PageView / page_view при смяна на страницата."],
        ["Разглеждане на продукт", "ViewContent / view_item на продуктова страница."],
        ["Добавяне в количка", "AddToCart / add_to_cart след успешно добавяне."],
        ["Започната поръчка", "InitiateCheckout / begin_checkout при checkout."],
        ["Завършена поръчка", "Purchase / purchase след реално потвърдена поръчка според имплементацията."],
      ].map(([name, purpose]) => toggleControl(`Събитие „${name}“`, purpose, "След Save събитието се изпраща само към активни providers и при съответното cookie consent.", { permission: "PRODUCTS:EDIT", customerImpact: "Може да изпрати marketing/analytics event след съгласие." })),
      button("Запази интеграциите", "Записва трите provider настройки и event набора трайно в local database.", "При успех се показва потвърждение и storefront използва новата конфигурация на всички production instances.", { permission: "PRODUCTS:EDIT", customerImpact: "Може да активира/спре production tracking.", avoid: ["Провери test mode, ID и consent преди Save." ] }),
    ],
    statuses: [{ name: "Активна", meaning: "Enabled е включено и ID не е празно.", next: "Провери consent и test/production поведението." }, { name: "Неактивна", meaning: "Enabled е изключено или ID липсва.", next: "Остави така, докато конфигурацията е потвърдена." }, { name: "Test mode", meaning: "Събитията се log-ват без външен pixel.", next: "Използвай за QA преди production." }],
    workflows: [workflow("configure-marketing", "Как да настроя marketing provider", "Да активираш Meta Pixel безопасно.", ["Вземи Pixel ID от официалния Meta Business account.", "Остави Активирай включено и включи Тестов режим.", "Въведи само ID, не код.", "Избери нужните events.", "Запази.", "При разрешени cookies тествай page, product, cart и checkout събитията в console.", "След одобрение изключи Test mode и повтори consent-aware проверката."], "Provider-ът изпраща само разрешени production events към правилния акаунт.", { permission: "PRODUCTS:EDIT" })],
    errors: [{ message: "Интеграциите не бяха запазени", meaning: "Permission, ID validation или server записът е отказан.", action: "Остави test mode и провери точния ID и PRODUCTS:EDIT правото." }],
    mistakes: ["Поставен script вместо ID.", "Чужд/test ID в production.", "Изключен consent контрол.", "Purchase event, приет за payment доказателство."],
    checklist: ["ID е от правилния account.", "Не съм поставил JavaScript.", "Test mode е проверен.", "Events са нужните.", "Cookie consent е спазен.", "Production поведението е проверено."],
    tips: ["Provider status Активна не означава, че tracking се изпраща без клиентско съгласие."],
    keywords: ["Google Analytics", "GTM", "Meta Pixel", "Facebook Pixel", "TikTok Pixel", "test mode", "cookie", "PageView", "Purchase"],
  }),

  topic({
    id: "social",
    title: "Социални мрежи: Facebook, Instagram и TikTok линкове",
    shortTitle: "Социални мрежи",
    hrefs: ["/admin/social-networks"],
    permission: "PRODUCTS:VIEW",
    summary: "Управлява публичните иконки и URL адреси в горната лента.",
    purpose: "Свързва клиента с официалните профили и скрива мрежи без валиден линк.",
    beginner: "Ако си тук за първи път, отметката сама не е достатъчна: иконката е активна само когато има и URL. Най-важно е да отвориш линка за проверка и да се увериш, че води към официалния профил, а не към личен или грешен account. Не използвай shortened URL, който не можеш да провериш.",
    whenToUse: ["За официален Facebook, Instagram или TikTok profile URL.", "За показване или скриване на иконка."],
    whenNotToUse: ["За marketing pixel ID.", "За лични профили без бизнес одобрение."],
    screen: ["Три карти с icon preview, status, enabled toggle, URL и test link.", "Save горе и долу."],
    controls: [
      toggleControl("Покажи иконката в горната лента", "Разрешава публичното показване на мрежата, ако URL не е празен.", "След Save иконката се показва или скрива.", { permission: "PRODUCTS:EDIT", customerImpact: "Променя публичната header лента." }),
      field("Линк към профил / страница", "Пълният официален URL за съответната мрежа.", "Пълен https:// URL към business profile/page.", "https://www.instagram.com/example-store", "След Save иконката отваря URL в нов tab, ако е enabled.", { permission: "PRODUCTS:EDIT", customerImpact: "Клиентът се изпраща към външния профил.", avoid: ["Не използвай личен, непълен или непроверен линк." ] }),
      button("Отвори линка за проверка", "Отваря текущия URL в нов tab преди Save или след редакция.", "Виждаш целевата външна страница.", { customerImpact: "Не променя магазина; отваря външен сайт." }),
      button("Запази социалните мрежи", "Записва enabled и URL за трите мрежи.", "При успех се показва потвърждение и публичните иконки се обновяват.", { permission: "PRODUCTS:EDIT", customerImpact: "Веднага може да промени публичните иконки." }),
    ],
    statuses: [{ name: "Активна", meaning: "Enabled е включено и URL е непразен.", next: "Тествай публичната иконка." }, { name: "Скрита", meaning: "Enabled е изключено или URL липсва.", next: "Остави скрита, докато има потвърден линк." }],
    workflows: [workflow("update-social", "Как да сменя social link", "Да обновиш Instagram без грешен публичен линк.", ["Постави пълния официален URL.", "Натисни Отвори линка за проверка.", "Провери името и съдържанието на профила.", "Включи Покажи иконката.", "Запази.", "Отвори storefront и натисни Instagram icon на desktop и mobile."], "Иконката води към правилния официален профил.", { permission: "PRODUCTS:EDIT" })],
    errors: [{ message: "Социалните мрежи не бяха запазени", meaning: "URL validation, permission или server записът е отказан.", action: "Провери пълния https URL и PRODUCTS:EDIT правото." }],
    mistakes: ["Enabled без URL.", "Грешен личен профил.", "Неизпитан линк.", "Бъркане на profile URL с Pixel ID."],
    checklist: ["URL е официален и https.", "Отворих го за проверка.", "Enabled е умишлено.", "Проверих публичната иконка."],
    tips: ["Скрий мрежата, ако официалният профил временно не е готов."],
    keywords: ["социални мрежи", "Facebook", "Instagram", "TikTok", "иконка", "линк", "URL"],
  }),

  topic({
    id: "visual-editor",
    title: "Визуален редактор: редакция, версии, Publish и rollback",
    shortTitle: "Визуален редактор",
    hrefs: ["/visual-editor", "/admin/web-design"],
    designOwnerOnly: true,
    summary: "Owner-only редактор за страници, текст, снимки, секции, меню, лого, цветове, footer и version history.",
    purpose: "Променя клиентския дизайн в preview, записва именувани версии и прилага дизайн към реалния магазин само след проверка.",
    beginner: "Ако си тук за първи път, това е най-публичната Admin зона: промените могат да се видят от всички клиенти. „Запиши“ създава именувана версия, а „Публикувай“ прилага текущия дизайн в реалния магазин. Най-важно е да провериш desktop, tablet и mobile преди Publish. Не изтривай версия или секция и не публикувай само защото preview изглежда добре в един размер.",
    whenToUse: ["За текст, изображения, лого, меню, цветове, footer и responsive настройки.", "За именувана версия преди съществена промяна.", "За Publish след full QA или rollback към проверена версия."],
    whenNotToUse: ["За редакция на продуктови данни.", "За store category filter без catalog проверка.", "Без необходимото WEB_DESIGN право."],
    screen: ["Горен toolbar с page selector, Хронология, Запиши, Публикувай и Затвори.", "Устройства, preset размер и zoom/fit.", "Preview canvas и инструментална лента.", "Inspector за избрания element.", "Save version и History dialogs."],
    controls: [
      selectControl("Страница", "Избира preview route: Начална, Дамско, Мъжко, Детско, Нови, Промоции, За нас, Контакти, Количка, Checkout, Login, Register, Account, Favorites, History или Search, плюс активни catalog sections.", "Начална страница", "Preview зарежда избраната route; данните не се публикуват само от избор.", { customerImpact: "Няма отражение от самия preview избор." }),
      button("Хронология", "Отваря version history за текущата theme.", "Показва именувани версии, current marker, Избери тема и Изтрий.", { customerImpact: "Самото отваряне не променя дизайна." }),
      button("Запиши", "Отваря dialog за име и създава version snapshot след потвърждение.", "При име поне 2 знака се записва нова версия в history.", { permission: "WEB_DESIGN:EDIT", customerImpact: "Записва history version, но не е задължително да публикува в production.", avoid: ["Използвай описателно име, не „test1“."] }),
      field("Име на версията", "Позволява по-късно да разпознаеш какво съдържа snapshot-ът.", "2–120 знака; конкретна промяна и/или дата.", "Нова начална страница – 07.08.2026", "Версията се появява в Хронология.", { permission: "WEB_DESIGN:EDIT", customerImpact: "Няма пряко отражение до прилагане/публикуване." }),
      button("Публикувай", "Прилага текущия design в реалния store без да създава автоматично нова version в този бутон.", "След success storefront използва текущия дизайн.", { permission: "WEB_DESIGN:PUBLISH", customerImpact: "Незабавно променя реалния клиентски интерфейс.", avoid: ["Преди Publish запиши версия и провери всички устройства, страници, линкове и текстове.", "Натисни веднъж и изчакай Прилага..." ] }),
      button("Затвори", "Затваря standalone editor window/tab или връща към Admin според browser context.", "Редакторът се затваря; незаписани локални промени може да бъдат загубени.", { customerImpact: "Няма пряко отражение." }),
      control({ name: "Компютър / Таблет / Телефон", kind: "button", purpose: "Сменя responsive preview mode.", when: "Провери всеки режим преди Publish.", how: ["Избери Компютър и провери layout.", "Избери Таблет.", "Избери Телефон и провери няколко widths."], after: "Променя само preview viewport.", customerImpact: "Няма отражение до Publish.", success: "Preview frame използва избраното устройство.", errors: [], avoid: ["Не приемай един viewport за достатъчен." ] }),
      selectControl("Размер на телефон", "Избира 360, 390 или 430 px mobile preset.", "Стандартен телефон · 390px", "Preview frame сменя ширината.", { customerImpact: "Няма отражение до Publish." }),
      control({ name: "Zoom − / slider / + / Побери", kind: "filter", purpose: "Управлява мащаба на preview, без да променя реалния design.", when: "Използвай за оглед и fit.", how: ["Намали или увеличи.", "Натисни Побери за frame fit.", "Не оценявай реални font размери само по zoom."], format: "Preview zoom.", example: "100%", after: "Променя само editor display.", customerImpact: "Няма отражение.", success: "Preview се побира и остава четим.", errors: [], avoid: ["Не бъркай zoom с responsive font scale." ] }),
      ...[
        ["Избор / Текст", "Избира page element и позволява inline/universal text редакция."],
        ["Снимка", "Отваря image inspector за избрания image slot."],
        ["Секции", "Управлява catalog sections/pages."],
        ["Меню", "Управлява navigation items, ред, visible и link."],
        ["Лого", "Качва/премахва лого и управлява desktop/mobile размер."],
        ["Цветове", "Управлява design token colors."],
        ["Footer", "Управлява footer съдържание и изображение."],
      ].map(([name, purpose]) => control({ name: `Инструмент „${name}“`, kind: "button", purpose, when: "Избери, когато редактираш този тип елемент.", how: ["Избери правилната страница.", "Натисни инструмента или елемента в preview.", "Промени inspector полето.", "Провери всички устройства."], after: "Променя текущия draft state; не е production до Publish.", customerImpact: "След Publish клиентът вижда промяната.", success: "Inspector и preview показват новата стойност.", errors: ["Upload или save error означава да не публикуваш."], avoid: ["Променяй един логически блок наведнъж."], permission: "WEB_DESIGN:EDIT" })),
      control({ name: "Качване / Смени изображение", kind: "field", purpose: "Качва logo, hero, page или footer asset според избрания slot.", when: "Използвай само с одобрен asset.", how: ["Провери позволения формат.", "Качи правилния файл.", "Изчакай upload.", "Провери crop, размер и четимост на три устройства."], format: "PNG, JPG, WEBP; logo може и SVG според съответния control.", example: "logo.svg или hero.webp", after: "Asset URL влиза в текущия draft.", customerImpact: "След Publish новото изображение е публично.", success: "Preview показва asset-а без broken image.", errors: ["Upload failure: не публикувай и провери System Health/Cloudinary."], avoid: ["Не качвай файл с неясни права, лични данни или неподходящ размер."], permission: "WEB_DESIGN:ASSETS" }),
      field("Текстово поле", "Редактира заглавия, subtitles, button labels и universal text според избрания inspector.", "Проверен публичен текст с правилен правопис и дължина.", "Нова колекция", "Draft и preview се обновяват; след Publish текстът е публичен.", { permission: "WEB_DESIGN:EDIT", customerImpact: "Клиентът вижда текста след Publish." }),
      field("Цвят", "Избира design token чрез color input.", "Hex/color picker стойност с достатъчен contrast.", "#5c0b2d", "Draft theme colors се обновяват.", { permission: "WEB_DESIGN:EDIT", customerImpact: "След Publish променя публичната палитра.", avoid: ["Провери contrast на текст, focus и buttons." ] }),
      field("Размер / отстояние / височина", "Range controls за logo width, border radius, mobile scale, padding и hero height.", "Използвай slider в разрешения диапазон и прегледай резултата.", "Mobile logo 140px; horizontal padding 16px", "Responsive design tokens се обновяват.", { permission: "WEB_DESIGN:EDIT", customerImpact: "След Publish влияе на layout и четимостта." }),
      button("+ Създай секция/страница", "Създава нов catalog section от editor.", "Новата секция се добавя и може да се включи в менюто.", { permission: "WEB_DESIGN:EDIT", customerImpact: "След activation/Publish може да стане публична.", avoid: ["Провери catalog structure и дублажи." ] }),
      button("Изтрий секцията", "Изтрива non-system section след server проверки.", "Секцията се премахва при успех.", { permission: "WEB_DESIGN:EDIT", customerImpact: "Може да премахне публична страница.", avoid: ["Провери продукти, категории и меню; system sections са защитени." ] }),
      button("+ Добави бутон", "Добавя navigation item.", "Появява се нов menu row с label, link, visible и target options.", { permission: "WEB_DESIGN:EDIT", customerImpact: "След Publish може да се появи публичен menu item." }),
      field("Име на menu item", "Публичният текст на навигационния бутон.", "Кратко име, което се побира на mobile.", "Обувки", "Draft menu label се обновява.", { permission: "WEB_DESIGN:EDIT", customerImpact: "След Publish клиентът вижда името." }),
      selectControl("Link на menu item", "Избира или въвежда целевата страница според UI.", "/obuvki", "След Publish menu item отваря избрания route.", { permission: "WEB_DESIGN:EDIT", customerImpact: "Определя къде се навигира клиентът.", avoid: ["Тествай link-а; не оставяй dead route." ] }),
      toggleControl("Видимост на menu item", "Показва или скрива конкретния navigation item.", "След Publish hidden item не се вижда в менюто, но route може още да е достъпен директно.", { permission: "WEB_DESIGN:EDIT", customerImpact: "Променя публичната навигация." }),
      button("↑ / ↓ menu item", "Променя реда в navigation.", "Draft menu order се обновява.", { permission: "WEB_DESIGN:EDIT", id: "reorder-menu" }),
      button("Изтрий menu item", "Премахва navigation item от draft.", "След Publish бутонът изчезва от менюто.", { permission: "WEB_DESIGN:EDIT", id: "delete-menu-item", customerImpact: "Променя публичната навигация след Publish." }),
      button("Избери тема / Възстанови версия", "Прилага избрана history version/theme към current design чрез restore flow.", "След success текущият design state се сменя към избраната версия.", { permission: "WEB_DESIGN:RESTORE", customerImpact: "При apply/publish може да върне целия публичен дизайн.", avoid: ["Провери версията, timestamp и preview; rollback може да замени по-нови промени." ] }),
      button("Изтрий версия", "Премахва history version.", "Версията изчезва и не може да се избира от този history списък.", { permission: "WEB_DESIGN:RESTORE", customerImpact: "Не сменя автоматично текущия публичен design, но премахва recovery point.", avoid: ["Не изтривай последната проверена recovery версия." ] }),
    ],
    statuses: [
      { name: "Draft / текущи промени", meaning: "Редакторът има локално/сървърно работно състояние, което не е непременно production.", next: "Провери и създай именувана версия." },
      { name: "Version", meaning: "Именуван snapshot в Хронология.", next: "Използвай за сравнение и recovery." },
      { name: "Текуща тема", meaning: "Версията/theme, приложена като current.", next: "Провери storefront." },
      { name: "Published / Приложен", meaning: "Дизайнът е приложен към реалния магазин.", next: "Направи production smoke check." },
      { name: "Owner-only", meaning: "Route и Help темата са достъпни само за design owner.", next: "Не опитвай permission обход." },
    ],
    workflows: [
      workflow("edit-publish", "Как да сменя текст, цвят или лого и да публикувам", "Да направиш проверена публична промяна.", ["Избери страницата.", "Създай/пази baseline version преди голяма промяна.", "Избери Текст, Цветове или Лого и промени само нужната стойност.", "Провери Компютър, Таблет, Телефон 360/390/430px.", "Провери menu, footer, links, images и text overflow.", "Натисни Запиши, дай ясно version име и изчакай.", "Натисни Публикувай веднъж след одобрение.", "Отвори реалния storefront в нов tab и направи smoke check."], "Промяната е versioned, responsive проверена и публикувана.", { permission: "WEB_DESIGN:PUBLISH" }),
      workflow("edit-menu", "Как да редактирам меню", "Да добавиш, скриеш, преместиш или пренасочиш item.", ["Отвори Menu tool.", "За нов item натисни + Добави бутон.", "Въведи кратко име и правилния route.", "Използвай visible checkbox за показване/скриване.", "Използвай стрелките за ред.", "Тествай link-а в preview и production след Publish.", "Изтрий само item, който вече не трябва да съществува."], "Менюто е четимо и всички видими links работят.", { permission: "WEB_DESIGN:EDIT" }),
      workflow("rollback-design", "Как да rollback-на дизайн", "Да върнеш проверена стара версия.", ["Отвори Хронология.", "Намери версията по име и дата.", "Провери дали е current или стара.", "Избери/възстанови версията и изчакай.", "Провери всички страници и устройства.", "Публикувай само ако restore flow не го е приложил автоматично и UI го изисква.", "Направи production smoke check."], "Възстановена е правилната версия без неволна загуба на по-нови нужни промени.", { permission: "WEB_DESIGN:RESTORE" }),
    ],
    errors: [
      { message: "Upload / Save / Apply error", meaning: "Draft или production промяната не е потвърдена.", action: "Не публикувай и не повтаряй многократно. Запази точния error и провери System Health." },
      { message: "Version name е твърде кратко", meaning: "Името е под 2 знака.", action: "Въведи конкретно име до 120 знака." },
      { message: "Preview не е готов", meaning: "Iframe още зарежда или route има проблем.", action: "Изчакай, провери избраната страница и не публикувай blank preview." },
    ],
    mistakes: ["Publish без version.", "Проверка само на desktop.", "Zoom, объркан с реален responsive размер.", "Грешен menu link.", "Изтриване на recovery version.", "Лого или image с broken URL."],
    checklist: ["Избрах правилната страница.", "Имам baseline/нова version.", "Промених само нужния inspector.", "Проверих desktop, tablet и 360/390/430 mobile.", "Всички текстове се побират.", "Всички links и assets работят.", "Публикувах веднъж и направих production smoke check."],
    tips: ["Запиши version преди и след голяма промяна с разбираеми имена."],
    keywords: ["visual editor", "дизайн", "текст", "цвят", "logo", "меню", "link", "save", "publish", "history", "rollback", "responsive", "mobile"],
  }),

  topic({
    id: "cms-models",
    title: "Content Model Studio: owner-only CMS модели",
    shortTitle: "CMS модели",
    hrefs: ["/admin/cms"],
    designOwnerOnly: true,
    summary: "Създава динамични content types и тяхната field структура.",
    purpose: "Позволява owner-only модели като Новини или Услуги, без промяна на React кода.",
    beginner: "Ако си тук за първи път, това е advanced owner-only инструмент, който определя структурата на бъдещо съдържание. Полето key се използва от API и templates, затова промяната му може да счупи връзки. Най-важно е да планираш модела преди да има записи. Не създавай модели за Store продукти, поръчки или RMA; те имат отделни реални модули.",
    whenToUse: ["Само за одобрен dynamic content тип.", "Преди създаване на entries."],
    whenNotToUse: ["За продукти, категории, orders или store business logic.", "От подадминистратор без design owner access."],
    screen: ["Списък Content Types.", "Editor за име, slug, icon, status и fields.", "Actions за content, delete, reset и save."],
    controls: [
      button("+ Нов модел", "Нулира editor за нов content type.", "Появява се празна форма с начално Title поле.", { customerImpact: "Няма публично отражение преди save и entries." }),
      field("Име в множествено число", "Името на колекцията.", "Ясно име.", "Новини", "Показва се в CMS list и UI.", { customerImpact: "Вътрешно, докато няма публичен template." }),
      field("Име в единствено число", "Името на един entry.", "Ясно име.", "Новина", "Използва се във формата Нов запис.", { customerImpact: "Вътрешно." }),
      field("Slug", "Стабилният content type identifier.", "Малки латински букви, цифри и тирета.", "news", "Използва се в API и бъдещи templates.", { customerImpact: "Може да участва в публични route-ове.", avoid: ["Не променяй след интеграция без migration план." ] }),
      field("Икона", "Кратък визуален symbol в CMS list.", "Един подходящ symbol/character.", "▦", "Показва се в CMS Admin.", { customerImpact: "Няма пряко отражение." }),
      field("Описание", "Обяснява целта на модела.", "Ясен вътрешен текст.", "Новини и прессъобщения.", "Показва се в Admin.", { customerImpact: "Няма пряко отражение." }),
      selectControl("Статус на модела", "Активира или спира content type.", "ACTIVE", "Моделът се записва като Активен или Спрян.", { customerImpact: "Може да влияе на използващите го templates." }),
      button("+ Добави поле", "Добавя нов field definition.", "Появява се ред с default name, key и TEXT type.", { customerImpact: "Няма отражение преди save." }),
      field("Име на поле", "Човешкото име във form UI.", "Ясно име.", "Заглавие", "Показва се в entry editor.", { customerImpact: "Няма пряко отражение." }),
      field("Ключ на поле", "Stable API/template key.", "Малки латински букви, цифри и underscore.", "title", "Данните на entries се съхраняват под този key.", { customerImpact: "Template може да чете стойността.", avoid: ["Не сменяй след entries/templates без migration." ] }),
      selectControl("Тип на поле", "Избира TEXT, RICH_TEXT, NUMBER, PRICE, BOOLEAN, DATE, IMAGE, GALLERY, VIDEO, RELATION, SELECT, MULTI_SELECT, JSON или FILE.", "RICH_TEXT", "Entry form генерира подходящ input.", { customerImpact: "Определя формата на бъдещото съдържание." }),
      toggleControl("Задължително", "Изисква стойност за field според API validation.", "След save field се маркира required.", { customerImpact: "Може да блокира entry save без стойност." }),
      toggleControl("Уникално", "Изисква стойността да е различна между entries, когато backend го прилага.", "След save field се маркира unique.", { customerImpact: "Може да блокира дублирани entries." }),
      button("Премахни поле", "Маха field definition от form; последното поле е защитено от disable.", "При save структурата се обновява.", { customerImpact: "Може да направи existing entry data недостъпна през form.", avoid: ["Не премахвай поле с реални данни без migration/backup." ] }),
      button("Създай CMS модел / Запази промените", "Създава или обновява content type и fields.", "При успех list се reload-ва и се показва success message.", { customerImpact: "Може да промени структурата на използвано съдържание." }),
      button("Съдържание", "Отваря entries за модела.", "Преминава към /admin/cms/{id}.", { customerImpact: "Самото отваряне не променя данни." }),
      button("Изтрий модел", "Изтрива content type след confirm и server checks.", "Моделът и зависимото съдържание се обработват според API.", { id: "delete-cms-model", customerImpact: "Може да премахне dynamic content.", avoid: ["Провери entries и публичните templates; използвай само с backup и одобрение." ] }),
      button("Отказ", "Нулира editor без server save.", "Незаписаните form промени се губят.", { customerImpact: "Няма отражение." }),
    ],
    statuses: [{ name: "ACTIVE", meaning: "Моделът е активен.", next: "Може да се управляват entries." }, { name: "INACTIVE", meaning: "Моделът е спрян.", next: "Провери consuming templates." }],
    workflows: [workflow("create-cms-model", "Как да създам CMS модел", "Да създадеш планиран модел Новини.", ["Опиши нужните fields на хартия/в задача.", "Въведи Новини, Новина и slug news.", "Добави fields title TEXT required, body RICH_TEXT required и date DATE.", "Провери keys и types.", "Създай модела.", "Отвори Съдържание и създай draft test entry.", "Тествай consuming template преди production publish."], "Моделът е стабилен и има проверен entry workflow." )],
    errors: [{ message: "CMS моделът не може да бъде зареден/записан", meaning: "Owner access, API, database или validation проблем.", action: "Не създавай store data в друг модул; запиши error и провери system health." }],
    mistakes: ["Store products като CMS.", "Промяна на key след entries.", "Изтриване на модел с content.", "Неподходящ field type."],
    checklist: ["Моделът е одобрен.", "Names и slug са стабилни.", "Всеки field key и type е проверен.", "Required/unique са умишлени.", "Има test entry и template QA."],
    tips: ["CMS е owner-only и не се показва на обикновен подадминистратор."],
    keywords: ["CMS", "content model", "content type", "field", "key", "dynamic content", "owner"],
  }),

  topic({
    id: "cms-entries",
    title: "CMS съдържание: draft, publish и archive entries",
    shortTitle: "CMS записи",
    hrefs: ["/admin/cms/:id"],
    designOwnerOnly: true,
    summary: "Owner-only динамични записи, генерирани от избрания content model.",
    purpose: "Създава, редактира, публикува, архивира и изтрива entries по стабилната CMS структура.",
    beginner: "Ако си тук за първи път, формата е различна за всеки модел. Заглавие, slug и статус винаги са основни, а останалите fields идват от модела. Най-важно е да започнеш като Чернова и да провериш публичния template преди Публикуван. Не въвеждай invalid JSON и не изтривай entry, ако Архивиран е достатъчно.",
    whenToUse: ["За одобрено dynamic content.", "За draft → published → archived lifecycle."],
    whenNotToUse: ["За store products/orders.", "Без design owner access."],
    screen: ["Back link, Нов запис, search и status filter.", "Entries list с status badge.", "Base fields и dynamic generated fields.", "Save/delete actions."],
    controls: [
      button("Content Models", "Връща към CMS model list.", "Отваря /admin/cms.", { customerImpact: "Няма отражение." }),
      button("+ Нов запис", "Нулира формата за нов entry.", "Появяват се празни base и model fields.", { customerImpact: "Няма отражение преди save." }),
      field("Търсене", "Намира entries по server criteria при Enter или Търси.", "Свободен текст.", "лятна колекция", "List се reload-ва.", { kind: "filter", customerImpact: "Няма отражение." }),
      button("Търси", "Изпълнява CMS entry search.", "List се обновява.", { customerImpact: "Няма отражение." }),
      selectControl("Статус филтър", "Показва Всички, Чернови, Публикувани или Архивирани.", "Чернови", "List се reload-ва.", { kind: "filter", customerImpact: "Няма отражение." }),
      field("Заглавие", "Основното човешко име на entry.", "Ясно заглавие.", "Лятна колекция 2026", "Показва се в Admin и може да се използва публично.", { customerImpact: "При Published може да се вижда от клиент." }),
      field("Slug", "URL identifier; може да се генерира от заглавието.", "Малки латински букви, цифри и тирета.", "summer-collection-2026", "Използва се от CMS entry и евентуален public route.", { customerImpact: "Може да промени публичния URL." }),
      selectControl("Статус", "Избира DRAFT, PUBLISHED или ARCHIVED.", "DRAFT", "При save entry се записва със статуса; publishedAt се управлява от backend.", { customerImpact: "PUBLISHED може да направи съдържанието публично, ако template го използва.", avoid: ["Започни с DRAFT." ] }),
      control({ name: "Динамични полета", kind: "field", purpose: "Генерират се от content model и могат да са text, rich text, number, price, boolean, date, URL, list или JSON.", when: "Попълни според label, type, required marker и description.", how: ["Прочети field name и description.", "Използвай правилния формат.", "За list: една стойност на ред.", "За JSON: валидна JSON структура.", "Провери required звездичките."], format: "Зависи от field type.", example: "PRICE 29.90; DATE 2026-08-07; BOOLEAN checked; MULTI_SELECT една стойност на ред.", after: "Data се записва под stable field key.", customerImpact: "Published template може да покаже стойностите.", success: "След save стойностите остават в editor.", errors: ["Invalid JSON може временно да се пази като text в client state, но API/template може да го откаже или интерпретира грешно."], avoid: ["Не поставяй executable code или чувствителни данни." ] }),
      button("Създай запис / Запази промените", "Създава или обновява entry.", "При успех list се reload-ва и form се reset-ва.", { customerImpact: "При PUBLISHED може да промени публичното съдържание." }),
      button("Изтрий entry", "Изтрива конкретния entry след confirm.", "Entry изчезва от list и consuming template може да остане без него.", { id: "delete-cms-entry", customerImpact: "Може да премахне публично съдържание.", avoid: ["Използвай ARCHIVED, когато съдържанието трябва да се пази исторически." ] }),
      button("Отказ", "Нулира form без save.", "Незаписаните промени се губят.", { customerImpact: "Няма отражение." }),
    ],
    statuses: [{ name: "DRAFT / Чернова", meaning: "Работен entry, който не трябва да се счита публикуван.", next: "Попълни и тествай." }, { name: "PUBLISHED / Публикуван", meaning: "Entry е разрешен за публична употреба.", next: "Провери consuming page." }, { name: "ARCHIVED / Архивиран", meaning: "Entry се пази, но не трябва да е активен.", next: "Предпочети пред delete за история." }],
    workflows: [workflow("publish-cms-entry", "Как да създам и публикувам CMS запис", "Да публикуваш проверена новина.", ["Натисни Нов запис.", "Въведи заглавие и стабилен slug.", "Остави DRAFT.", "Попълни всички required dynamic fields.", "Създай записа.", "Провери preview/consuming template.", "Отвори entry, смени status на PUBLISHED и Запази.", "Провери public page на desktop/mobile."], "Записът е публикуван само след content QA." )],
    errors: [{ message: "Записът беше неуспешен", meaning: "Field validation, permission или API проблем.", action: "Провери required fields, slug, JSON и content model." }],
    mistakes: ["PUBLISHED от първия save.", "Невалиден slug.", "List data в един ред вместо един item на ред.", "Delete вместо archive."],
    checklist: ["Заглавието и slug са правилни.", "Required fields са попълнени.", "Status започна DRAFT.", "Template е проверен.", "Public page е тествана след publish."],
    tips: ["Ако формата има неочаквани fields, върни се към Content Models и провери структурата, без да я променяш прибързано."],
    keywords: ["CMS entry", "чернова", "draft", "published", "archived", "dynamic fields", "JSON", "slug"],
  }),
];
