"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import styles from "./CatalogSettingsManager.module.css";

type Category={id:number;name:string;slug:string;isActive:boolean;sortOrder:number};
type Attr={key:string;label:string;type:string;required?:boolean;options?:string[]};
type BaseType={id:number;name:string;slug:string;legacyType:string;defaultSizeMode:string;defaultSizeOptions:unknown;attributes:unknown;isActive:boolean;sortOrder:number};
type ProductTypeDef={id:number;name:string;slug:string;baseTypeId:number|null;legacyType:string;sizeMode:string;sizeOptions:unknown;attributes:unknown;isActive:boolean;sortOrder:number};
const toLines=(v:unknown)=>Array.isArray(v)?v.join("\n"):"";
const attrs=(v:unknown)=>Array.isArray(v)?v as Attr[]:[];
const blankAttr=()=>({key:`field_${Date.now()}`,label:"",type:"text",required:false});
const legacyOptions=<><option value="CLOTHING">Дреха</option><option value="SHOES">Обувки</option><option value="ACCESSORY">Аксесоар</option></>;
const sizeOptions=<><option value="CLOTHING">Номерация дрехи</option><option value="SHOES">Номерация обувки</option><option value="CM">Размери в сантиметри</option><option value="CUSTOM">Персонализирани</option><option value="NONE">Без размери</option></>;

export default function CatalogSettingsManager({initialCategories,initialBaseTypes,initialTypes}:{initialCategories:Category[];initialBaseTypes:BaseType[];initialTypes:ProductTypeDef[]}){
 const router=useRouter(); const [categories,setCategories]=useState(initialCategories); const [baseTypes,setBaseTypes]=useState(initialBaseTypes); const [types,setTypes]=useState(initialTypes); const [message,setMessage]=useState("");
 async function send(url:string,method:string,body?:unknown){setMessage("");const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok){setMessage(j.error||"Грешка.");return false;}setMessage("Промените са запазени.");router.refresh();return true;}
 function copyBaseToType(index:number,baseId:number){const b=baseTypes.find(x=>x.id===baseId);setTypes(v=>v.map((x,n)=>n===index?{...x,baseTypeId:baseId||null,legacyType:b?.legacyType||x.legacyType,sizeMode:b?.defaultSizeMode||x.sizeMode,sizeOptions:b?.defaultSizeOptions||x.sizeOptions,attributes:b?.attributes||x.attributes}:x));}
 return <div className={styles.wrap}>
  {message&&<div className={styles.message}>{message}</div>}
  <section className={`${styles.card} ${styles.baseCard}`}><div className={styles.heading}><div><span>НИВО 1 · ШАБЛОНИ</span><h2>Продуктови семейства</h2></div><p>Това са общите шаблони — например „Дрехи“, „Обувки“ или „Електроника“. Те задават наследени размери и параметри за всички свързани конкретни типове.</p></div><div className={styles.levelHint}><b>Пример:</b> Семейство „Дрехи“ → типове „Тениска“, „Рокля“, „Яке“.</div>
   <button className={styles.add} onClick={()=>setBaseTypes(v=>[...v,{id:0,name:"Нов базов тип",slug:"nov-bazov-tip",legacyType:"CLOTHING",defaultSizeMode:"CUSTOM",defaultSizeOptions:[],attributes:[],isActive:true,sortOrder:100}])}>+ Ново продуктово семейство</button>
   <div className={styles.typeGrid}>{baseTypes.map((b,i)=><article className={styles.typeCard} key={`${b.id}-${i}`}>
    <div className={styles.two}><label>Име<input value={b.name} onChange={e=>setBaseTypes(v=>v.map((x,n)=>n===i?{...x,name:e.target.value}:x))}/></label><label>Slug<input value={b.slug} onChange={e=>setBaseTypes(v=>v.map((x,n)=>n===i?{...x,slug:e.target.value}:x))}/></label></div>
    <div className={styles.two}><label>Техническа съвместимост<select value={b.legacyType} onChange={e=>setBaseTypes(v=>v.map((x,n)=>n===i?{...x,legacyType:e.target.value}:x))}>{legacyOptions}</select></label><label>Размерна система<select value={b.defaultSizeMode} onChange={e=>setBaseTypes(v=>v.map((x,n)=>n===i?{...x,defaultSizeMode:e.target.value}:x))}>{sizeOptions}</select></label></div>
    <label>Размери / номерация по подразбиране<textarea value={toLines(b.defaultSizeOptions)} onChange={e=>setBaseTypes(v=>v.map((x,n)=>n===i?{...x,defaultSizeOptions:e.target.value.split("\n").map(s=>s.trim()).filter(Boolean)}:x))}/></label>
    <div className={styles.attributes}><b>Наследени параметри</b>{attrs(b.attributes).map((a,ai)=><div className={styles.attr} key={ai}><input placeholder="Име на поле" value={a.label} onChange={e=>setBaseTypes(v=>v.map((x,n)=>n===i?{...x,attributes:attrs(x.attributes).map((q,k)=>k===ai?{...q,label:e.target.value}:q)}:x))}/><select value={a.type} onChange={e=>setBaseTypes(v=>v.map((x,n)=>n===i?{...x,attributes:attrs(x.attributes).map((q,k)=>k===ai?{...q,type:e.target.value}:q)}:x))}><option value="text">Текст</option><option value="number">Число</option><option value="select">Списък</option></select><label><input type="checkbox" checked={!!a.required} onChange={e=>setBaseTypes(v=>v.map((x,n)=>n===i?{...x,attributes:attrs(x.attributes).map((q,k)=>k===ai?{...q,required:e.target.checked}:q)}:x))}/> Задължително</label><button className={styles.danger} onClick={()=>setBaseTypes(v=>v.map((x,n)=>n===i?{...x,attributes:attrs(x.attributes).filter((_,k)=>k!==ai)}:x))}>×</button></div>)}<button onClick={()=>setBaseTypes(v=>v.map((x,n)=>n===i?{...x,attributes:[...attrs(x.attributes),blankAttr()]}:x))}>+ Параметър</button></div>
    <div className={styles.actions}><label><input type="checkbox" checked={b.isActive} onChange={e=>setBaseTypes(v=>v.map((x,n)=>n===i?{...x,isActive:e.target.checked}:x))}/> Активен</label><button onClick={async()=>{const ok=await send(b.id?`/api/admin/catalog/base-types/${b.id}`:"/api/admin/catalog/base-types",b.id?"PATCH":"POST",b);if(ok&&!b.id)location.reload()}}>Запази семейството</button>{b.id>0&&<button className={styles.danger} onClick={async()=>{if(confirm("Да изтрия ли продуктовото семейство?")&&await send(`/api/admin/catalog/base-types/${b.id}`,"DELETE"))setBaseTypes(v=>v.filter(x=>x.id!==b.id))}}>Изтрий</button>}</div>
   </article>)}</div>
  </section>

  <section className={styles.card}><div className={styles.heading}><div><span>КАТАЛОГ</span><h2>Категории</h2></div><p>Добавяй, преименувай, подреждай, деактивирай или изтривай категории.</p></div>
   <button className={styles.add} onClick={()=>setCategories(v=>[...v,{id:0,name:"Нова категория",slug:"nova-kategoriya",isActive:true,sortOrder:100}])}>+ Нова категория</button>
   <div className={styles.list}>{categories.map((c,i)=><div className={styles.row} key={`${c.id}-${i}`}><input value={c.name} onChange={e=>setCategories(v=>v.map((x,n)=>n===i?{...x,name:e.target.value}:x))}/><input value={c.slug} onChange={e=>setCategories(v=>v.map((x,n)=>n===i?{...x,slug:e.target.value}:x))}/><input type="number" value={c.sortOrder} onChange={e=>setCategories(v=>v.map((x,n)=>n===i?{...x,sortOrder:Number(e.target.value)}:x))}/><label><input type="checkbox" checked={c.isActive} onChange={e=>setCategories(v=>v.map((x,n)=>n===i?{...x,isActive:e.target.checked}:x))}/> Активна</label><button onClick={async()=>{const ok=await send(c.id?`/api/admin/catalog/categories/${c.id}`:"/api/admin/catalog/categories",c.id?"PATCH":"POST",c);if(ok&&!c.id)location.reload()}}>Запази</button>{c.id>0&&<button className={styles.danger} onClick={async()=>{if(confirm("Да изтрия ли категорията?")&&await send(`/api/admin/catalog/categories/${c.id}`,"DELETE"))setCategories(v=>v.filter(x=>x.id!==c.id))}}>Изтрий</button>}</div>)}</div>
  </section>

  <section className={`${styles.card} ${styles.productTypeCard}`}><div className={styles.heading}><div><span>НИВО 2 · КОНКРЕТНИ ТИПОВЕ</span><h2>Типове продукти</h2></div><p>Това са конкретните видове артикули — например „Тениска“, „Маратонки“ или „Смартфон“. Всеки тип избира продуктово семейство и може да добави собствени размери и параметри.</p></div><div className={styles.levelHint}><b>Наследяване:</b> Типът получава настройките от семейството, но може да ги надгради.</div>
   <button className={styles.add} onClick={()=>setTypes(v=>[...v,{id:0,name:"Нов тип",slug:"nov-tip",baseTypeId:baseTypes[0]?.id||null,legacyType:baseTypes[0]?.legacyType||"CLOTHING",sizeMode:baseTypes[0]?.defaultSizeMode||"CUSTOM",sizeOptions:baseTypes[0]?.defaultSizeOptions||[],attributes:baseTypes[0]?.attributes||[],isActive:true,sortOrder:100}])}>+ Нов тип продукт</button>
   <div className={styles.typeGrid}>{types.map((t,i)=><article className={styles.typeCard} key={`${t.id}-${i}`}>
    <div className={styles.two}><label>Име<input value={t.name} onChange={e=>setTypes(v=>v.map((x,n)=>n===i?{...x,name:e.target.value}:x))}/></label><label>Slug<input value={t.slug} onChange={e=>setTypes(v=>v.map((x,n)=>n===i?{...x,slug:e.target.value}:x))}/></label></div>
    <div className={styles.two}><label>Продуктово семейство<select value={t.baseTypeId||0} onChange={e=>copyBaseToType(i,Number(e.target.value))}><option value={0}>Без продуктово семейство</option>{baseTypes.filter(b=>b.isActive).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Режим размери<select value={t.sizeMode} onChange={e=>setTypes(v=>v.map((x,n)=>n===i?{...x,sizeMode:e.target.value}:x))}>{sizeOptions}</select></label></div>
    <label>Размери / номерация — по един на ред<textarea value={toLines(t.sizeOptions)} onChange={e=>setTypes(v=>v.map((x,n)=>n===i?{...x,sizeOptions:e.target.value.split("\n").map(s=>s.trim()).filter(Boolean)}:x))}/></label>
    <div className={styles.attributes}><b>Допълнителни параметри</b>{attrs(t.attributes).map((a,ai)=><div className={styles.attr} key={ai}><input placeholder="Име на поле" value={a.label} onChange={e=>setTypes(v=>v.map((x,n)=>n===i?{...x,attributes:attrs(x.attributes).map((q,k)=>k===ai?{...q,label:e.target.value}:q)}:x))}/><select value={a.type} onChange={e=>setTypes(v=>v.map((x,n)=>n===i?{...x,attributes:attrs(x.attributes).map((q,k)=>k===ai?{...q,type:e.target.value}:q)}:x))}><option value="text">Текст</option><option value="number">Число</option><option value="select">Списък</option></select><label><input type="checkbox" checked={!!a.required} onChange={e=>setTypes(v=>v.map((x,n)=>n===i?{...x,attributes:attrs(x.attributes).map((q,k)=>k===ai?{...q,required:e.target.checked}:q)}:x))}/> Задължително</label><button className={styles.danger} onClick={()=>setTypes(v=>v.map((x,n)=>n===i?{...x,attributes:attrs(x.attributes).filter((_,k)=>k!==ai)}:x))}>×</button></div>)}<button onClick={()=>setTypes(v=>v.map((x,n)=>n===i?{...x,attributes:[...attrs(x.attributes),blankAttr()]}:x))}>+ Параметър</button></div>
    <div className={styles.actions}><label><input type="checkbox" checked={t.isActive} onChange={e=>setTypes(v=>v.map((x,n)=>n===i?{...x,isActive:e.target.checked}:x))}/> Активен</label><button onClick={async()=>{const ok=await send(t.id?`/api/admin/catalog/product-types/${t.id}`:"/api/admin/catalog/product-types",t.id?"PATCH":"POST",t);if(ok&&!t.id)location.reload()}}>Запази типа</button>{t.id>0&&<button className={styles.danger} onClick={async()=>{if(confirm("Да изтрия ли типа?")&&await send(`/api/admin/catalog/product-types/${t.id}`,"DELETE"))setTypes(v=>v.filter(x=>x.id!==t.id))}}>Изтрий</button>}</div>
   </article>)}</div>
  </section>
 </div>
}
