"use client";
import { useState } from "react";
import SizeGuideTypeSelect from "./SizeGuideTypeSelect";
import SizeGuideDiagram from "@/components/SizeGuideDiagram";
import { getSizeGuideType } from "@/lib/size-guide-types";

export type ManualMeasurement = { key:string; label:string; marker:string; unit:string; startX:number; startY:number; endX:number; endY:number };
export type ManualSizeRow = { key:string; label:string; values:Record<string,string> };
export type ManualSizeGuide = { name:string; garmentType:string; description:string; instructions:string; showDiagram:boolean; measurements:ManualMeasurement[]; sizes:ManualSizeRow[] };
const positioned=(items:Array<{label:string;marker:string}>)=>items.map((item,index)=>({key:`measurement-${crypto.randomUUID()}`,marker:item.marker||String.fromCharCode(65+index),label:item.label,unit:"cm",startX:index%2===0?24:38,startY:25+index*8,endX:index%2===0?76:62,endY:25+index*8}));
const emptyGuide=():ManualSizeGuide=>({name:"Индивидуални размери за този модел",garmentType:"TSHIRT",showDiagram:true,description:"Размерите на този модел са индивидуални и може да се различават от стандартните.",instructions:"Сравнете мерките от таблицата с дреха, която Ви стои добре, преди да поръчате.",measurements:[{key:"measurement-a",marker:"A",label:"Рамене",unit:"cm",startX:25,startY:28,endX:75,endY:28},{key:"measurement-b",marker:"B",label:"Гръдна обиколка",unit:"cm",startX:28,startY:44,endX:72,endY:44},{key:"measurement-c",marker:"C",label:"Дължина",unit:"cm",startX:62,startY:30,endX:62,endY:80}],sizes:[]});
export function createEmptyManualGuide(){return emptyGuide()}
export default function ManualProductSizeGuideEditor({value,onChange}:{value:ManualSizeGuide;onChange:(value:ManualSizeGuide)=>void}){
 const [selected,setSelected]=useState(0); const patch=(next:Partial<ManualSizeGuide>)=>onChange({...value,...next});
 function addMeasurement(){const index=value.measurements.length;const marker=String.fromCharCode(65+index);patch({measurements:[...value.measurements,{key:crypto.randomUUID(),marker,label:"Ново измерване",unit:"cm",startX:28,startY:25+index*7,endX:72,endY:25+index*7}]});setSelected(index)}
 function removeMeasurement(key:string){patch({measurements:value.measurements.filter(x=>x.key!==key),sizes:value.sizes.map(row=>{const values={...row.values};delete values[key];return{...row,values}})});setSelected(0)}
 function addSize(){patch({sizes:[...value.sizes,{key:crypto.randomUUID(),label:"S",values:{}}]})}
 return <div className="manualSizeEditor"><div className="manualSizeNotice"><strong>⚠ Индивидуален размер за този модел</strong><span>Тази таблица няма да се добавя към общите размерни стандарти. Клиентът ще бъде предупреден да провери мерките.</span></div><div className="manualSizeGrid"><label>Име на таблицата<input value={value.name} onChange={e=>patch({name:e.target.value})}/></label><label>Точен тип на артикула<SizeGuideTypeSelect value={value.garmentType} onChange={nextType=>{const measurements=positioned(getSizeGuideType(nextType).measurements);patch({garmentType:nextType,measurements,sizes:value.sizes.map(row=>({...row,values:{}}))});setSelected(0)}}/></label></div><label>Предупреждение към клиента<textarea rows={2} value={value.description} onChange={e=>patch({description:e.target.value})}/></label><label>Как да измери<textarea rows={3} value={value.instructions} onChange={e=>patch({instructions:e.target.value})}/></label>
 <label className="manualDiagramToggle"><input type="checkbox" checked={value.showDiagram !== false} onChange={e=>patch({showDiagram:e.target.checked})}/><span><strong>Показвай визуална схема</strong><small>Може да остане само таблицата с размери и мерки.</small></span></label>
 {value.showDiagram !== false && <div className="manualDiagramGrid"><div><h3>Схема на индивидуалните мерки</h3><p>Постави всяка линия точно там, където клиентът трябва да измери.</p><SizeGuideDiagram garmentType={value.garmentType} measurements={value.measurements} editable selectedIndex={selected} onSelect={setSelected} onChange={(index,change)=>patch({measurements:value.measurements.map((item,i)=>i===index?{...item,...change}:item)})}/></div><div><div className="manualSizeHeading"><h3>Измервания</h3><button type="button" onClick={addMeasurement}>+ Добави измерване</button></div><div className="manualMeasurements">{value.measurements.map((measurement,index)=><div className={`manualMeasurementRow ${selected===index?'manualMeasurementSelected':''}`} key={measurement.key} onClick={()=>setSelected(index)}><input aria-label="Маркер" value={measurement.marker} onChange={e=>patch({measurements:value.measurements.map((m,i)=>i===index?{...m,marker:e.target.value}:m)})}/><input aria-label="Измерване" value={measurement.label} onChange={e=>patch({measurements:value.measurements.map((m,i)=>i===index?{...m,label:e.target.value}:m)})}/><select value={measurement.unit} onChange={e=>patch({measurements:value.measurements.map((m,i)=>i===index?{...m,unit:e.target.value}:m)})}><option value="cm">cm</option><option value="mm">mm</option></select><button type="button" onClick={e=>{e.stopPropagation();removeMeasurement(measurement.key)}}>Премахни</button></div>)}</div></div></div>}
 <div className="manualSizeHeading"><h3>Размери и точни мерки</h3><button type="button" onClick={addSize}>+ Добави размер</button></div><div className="manualTableWrap"><table className="manualSizeTable"><thead><tr><th>Размер</th>{value.measurements.map(m=><th key={m.key}>{m.marker}<small>{m.label}</small></th>)}<th/></tr></thead><tbody>{value.sizes.map((row,rowIndex)=><tr key={row.key}><td><input value={row.label} onChange={e=>patch({sizes:value.sizes.map((r,i)=>i===rowIndex?{...r,label:e.target.value}:r)})}/></td>{value.measurements.map(m=><td key={m.key}><input inputMode="decimal" placeholder="—" value={row.values[m.key]??""} onChange={e=>patch({sizes:value.sizes.map((r,i)=>i===rowIndex?{...r,values:{...r.values,[m.key]:e.target.value}}:r)})}/></td>)}<td><button type="button" onClick={()=>patch({sizes:value.sizes.filter((_,i)=>i!==rowIndex)})}>×</button></td></tr>)}</tbody></table></div></div>
}
